### ISSUE TITLE
Some bizarre overlaps in glyphs

### ISSUE THREAD

**Issue by cssobral2013** [weiweihuanghuang/Prodigy-Sans#2]
If you need, see picture below. All Italic weights display this issue. (Note:I used WPS Office for Android because it's the ONLY app I can test for now, but every app and OS appears to display this issue.)

![Screenshot_20201008-194830](https://user-images.githubusercontent.com/19995437/95521311-a2295580-099f-11eb-87fe-786bf543fad7.png)

**Comment by weiweihuanghuang** [comment]
That is definitely a mistake and I will fix it soon 😅

**Comment by weiweihuanghuang** [comment]
Fixed
